### ISSUE TITLE
package.json缺少webpack-dev-server依赖。

### ISSUE THREAD

**Issue by elevensky** [superalsrk/koa2-boilerplate#1]
npm run dev error.
貌似：这个dev脚本里指定的--content-base ./server/public没有啊。

**Comment by superalsrk** [comment]
@elevensky  谢谢提醒。。已经fix, 如果想在本地进行开发的话, 可以参考这个wiki: https://github.com/superalsrk/koa2-boilerplate/wiki/develop-and-deploy.md
